### ISSUE TITLE
day pane 设置限制错误

### ISSUE THREAD

**Issue by jinpengqiong** [wangzongming/qnn-react-cron#11]
<img width="1734" alt="image" src="https://user-images.githubusercontent.com/33460394/163333043-61802162-642e-431a-892d-8f1ebf54fc04.png">
这里应该是30天或31天，不应该是23的限制。

**Comment by wangzongming** [comment]
这就是个区间，如果想要每天执行可以用一下方法设置
1、直接选择 每一日
2、从 1 日开始， 每 1 日执行一次
2、指定后全部选择

**Comment by wangzongming** [comment]
最新版已修改为 31天
