### ISSUE TITLE
反解析到UI时为什么‘指定年’和‘从xx年开始，每几年执行一次’这两个反不到UI 上 

### ISSUE THREAD

**Issue by wjin1212** [wangzongming/qnn-react-cron#12]

**Comment by wangzongming** [comment]
我测试了一遍，没有发现反解析有问题，你在确认下是不是你自己代码的问题

**Comment by wjin1212** [comment]
我直接复制了您使用方法里的代码，只修改了value的值，也无任何报错信息，其他都可以根据value值解析到UI，只有这两个不知道问什么不能。

**Comment by wjin1212** [comment]
例如：直接设置value为0 0 0 1 1 ? 2023,2022 ，‘年’不能再次回在组件上

**Comment by wangzongming** [comment]
按组件值的规范来
![image](https://user-images.githubusercontent.com/27466569/165001702-d069fee4-3a2f-4d33-b7b5-763da297c3dc.png)
