### ISSUE TITLE
JSX element type 'Cron' does not have any construct or call signatures.

### ISSUE THREAD

**Issue by yuxuejiao** [wangzongming/qnn-react-cron#13]
Hi, when I use the qnn-react-cron，I encounter the problem: JSX element type 'Cron' does not have any construct or call signatures.  See the images below for details.
<img width="1410" alt="Screen Shot 2022-05-17 at 5 28 30 PM" src="https://user-images.githubusercontent.com/18752571/168779286-7f0f4b3b-0c4c-4a18-b19d-d858e7252516.png">
<img width="1410" alt="Screen Shot 2022-05-17 at 5 28 48 PM" src="https://user-images.githubusercontent.com/18752571/168779310-a5dc79d2-f142-4ec3-a80a-78e4261068c7.png">
<img width="1441" alt="Screen Shot 2022-05-17 at 5 29 14 PM" src="https://user-images.githubusercontent.com/18752571/168779327-79b06ad9-f2de-457a-80cb-91d075ac385e.png">

The packages I used below:
"react": "17.0.2",
"typescript": "4.4.4",
"antd": "^4.19.5"

**Comment by wangzongming** [comment]
` npm i qnn-react-cron`
  Have you installed it？

**Comment by wangzongming** [comment]
I have no problem here. 
Check the TS configuration or whether qnn-react-cron is not installed

![image](https://user-images.githubusercontent.com/27466569/168782703-e7b7a5f5-4353-4f21-a8fb-676415921ccc.png)

**Comment by yuxuejiao** [comment]
<img width="1104" alt="Screen Shot 2022-05-18 at 9 39 33 AM" src="https://user-images.githubusercontent.com/18752571/168939585-93d2ea44-869a-469c-97cb-5939a936b0ae.png">
I have installed it.

**Comment by wangzongming** [comment]
> installed

Do you see any in node_modules?

**Or you check your ts configuration.**

**Comment by yuxuejiao** [comment]
<img width="1446" alt="Screen Shot 2022-05-18 at 10 02 03 AM" src="https://user-images.githubusercontent.com/18752571/168941858-e90005d4-36cc-4cb9-bde5-fc43fbc955ec.png">
For I use yarn, which is a different package management tool, in node_modules file, there is nothing.

**Comment by wangzongming** [comment]
> 
Yarn will also download the package to node_modules, otherwise the download is not successful.

**Comment by wangzongming** [comment]
The package needs to be in node_modules, otherwise it is not supported

**Comment by yuxuejiao** [comment]
> > 
> 
> Yarn will also download the package to node_modules, otherwise the download is not successful.

The new version of yarn not support download the package to node_modules, there is any solution?

**Comment by wangzongming** [comment]
> > > 
> > 
> > 
> > Yarn will also download the package to node_modules, otherwise the download is not successful.
> 
> The new version of yarn not support download the package to node_modules, there is any solution?

you can add file  in ` src/custom.d.ts`
then add content: 
`
declare module "qnn-react-cron" {
	export default any;
}
`

**Comment by wangzongming** [comment]
> > > > 
> > > 
> > > 
> > > Yarn will also download the package to node_modules, otherwise the download is not successful.
> > 
> > 
> > The new version of yarn not support download the package to node_modules, there is any solution?
> 
> you can add file ` src/custom.d.ts` then add content: `declare module "qnn-react-cron" { export default any; }`

This solution, if you need to ts, described here: 
https://github.com/wangzongming/qnn-react-cron#typescript-%E6%8E%A5%E5%8F%A3
