### ISSUE TITLE
在引入qnn-react-cron之后，对antd的样式造成了影响

### ISSUE THREAD

**Issue by yuxuejiao** [wangzongming/qnn-react-cron#14]
原来的样式：
<img width="893" alt="Screen Shot 2022-06-09 at 1 48 02 PM" src="https://user-images.githubusercontent.com/18752571/172773861-da35b163-caf9-4376-a2fa-6af3b85eff09.png">
在引入qnn-react-cron之后的样式：
<img width="639" alt="Screen Shot 2022-06-09 at 1 50 10 PM" src="https://user-images.githubusercontent.com/18752571/172773929-dde81061-392d-41be-8d22-89077398f27c.png">
select框，button的颜色都受到了影响

PS: 在app.ts文件里面 引入antd样式相关的代码： import 'antd/dist/antd.dark.less';

**Comment by wangzongming** [comment]
用的哪个版本的 qnn-react-cron?

**Comment by yuxuejiao** [comment]
> 用的哪个版本的 qnn-react-cron?

 "qnn-react-cron": "^0.8.6"

**Comment by wangzongming** [comment]
引入 import "antd/dist/antd.dark.css"; 试下呢？
引入 less 文件不确实你那里有没有更改 antd 那个按需加载的 webpack 配置

**Comment by yuxuejiao** [comment]
> import "antd/dist/antd.dark.css";

试了还是一样的

**Comment by wangzongming** [comment]
我这里是正常的。
![image](https://user-images.githubusercontent.com/27466569/172802599-347ba3f4-c88f-4372-bcea-e9c0796021fb.png)

webpack 配置在 babel-loader 中增加插件 

```
[
"import",
{
	libraryName: "antd",
	libraryDirectory: "es",
	style: "css",
},
"ant",
],
```

app.ts 中引入 
`import "antd/dist/antd.dark.css";`

最后设置一个样式
```
.qnn-react-cron {
    background-color: #000;
}

```
