### ISSUE TITLE
你好，你的.d.ts有点问题

### ISSUE THREAD

**Issue by forget-forever** [wangzongming/qnn-react-cron#15]
冒昧的问一句你的.d.ts是自己手写的吗。0.8.6版本中那个.d.ts有点问题。需要声明，导出default才可以，要不然使用的时候ts会报错
![image](https://user-images.githubusercontent.com/49786633/173513467-ab72d09b-4055-425c-8ed8-26e1127d2306.png)

**Comment by wangzongming** [comment]
你可以使用 
`import * as QnnCron from "qnn-react-cron"`  

或者直接改一下 `tsconfig.json` 也可以
`compilerOptions.allowSyntheticDefaultImports: true`

**Comment by wangzongming** [comment]
插件是使用 js 来写的，所以没有用直接生成声明文件，.d.ts 里面我只是手动把输入和输出描述了一下。

**Comment by forget-forever** [comment]
是的，我这边就是这样解决的，感谢啦

**Comment by wangzongming** [comment]
> 是的，我这边就是这样解决的，感谢啦

不客气
