### ISSUE TITLE
在默认每秒的基础上想要切换到每分的场景

### ISSUE THREAD

**Issue by yuxuejiao** [wangzongming/qnn-react-cron#16]
<img width="1777" alt="Screen Shot 2022-06-15 at 10 30 54" src="https://user-images.githubusercontent.com/18752571/173724226-2b2c2bd5-cf7d-4ca4-84e5-0882492bf146.png">
打开readme里面的预览地址，一直出不来具体的例子。

我的问题是：
目前我在本地试的时候，给了个默认值 * * * * * ? *， 默认进去，每秒，每分，每小时，每天等单选框都是默认选中的，实际上执行就是每秒执行一次，那如果我想切换到每分，因为已经默认选中了，那怎么操作的？

**Comment by yuxuejiao** [comment]
为什么在秒/分...这些tab下面，是单选项，如果不考虑秒和其他选项的情况，只考虑分，那秒和其他选项已选中的项就不能取消了么？

**Comment by wangzongming** [comment]
感谢反馈，这个codesandbox 可能坏掉了...，后期我再换一个延时地址。

对于你提出这个问题，我给组件的秒、分、时都增加了 不指定选项。更新组件至 1.0.0 即可
