### ISSUE TITLE
月份天数问题

### ISSUE THREAD

**Issue by fuchaohui** [wangzongming/qnn-react-cron#17]
作者大大，非常感谢你的分享，但在使用的时候发现了一个小bug，不同的月份，应该对应不同的天数，而组件对天数的控制全部都是定死31天。

**Comment by wangzongming** [comment]
这个限制没有必要的，因为月份可以选择多个，当选择多个时候这个就失去了意义，选择某一个月执行的情况也比较少。

**Comment by fuchaohui** [comment]
但如果选择多个月份，如4，6，9，11   月份，这些月份只有30天，此时天数还出现31天感觉不太好。而且有的用户需求也可能就需要某个月份的某一天，这样的话体验感就不太好。

**Comment by wangzongming** [comment]
> 而且有的用户需求也可能就需要某个月份的

你这个需求属于没必要的。 1 3 5 7 8 10 腊  31 天永不差。2 月还有 28 或者 29 天。
要根据当前年份、月份，在结合用户选择的月份来控制那一个复选框是否可选择... 
能用这个控件的客户应该不会不知道 31 号这个规则...

这个需求没啥必要满足。毕竟 31 天全部情况都是通用的。
