### ISSUE TITLE
生成的cron表达式java的Quartz才能解析，有没有是Java的Spring无法解析

### ISSUE THREAD

**Issue by is-cool** [wangzongming/qnn-react-cron#18]
生成的cron表达式java的Quartz才能解析，有没有是Java的Spring无法解析，可以切换格式嘛。
<img width="855" alt="截屏2022-07-06 17 09 04" src="https://user-images.githubusercontent.com/78067806/177515584-9212fcaa-bf2b-4cec-9975-f03c62b0e56f.png">

**Comment by wangzongming** [comment]
这个功能你可以根据组件的值自行实现的喔。或者能帮忙提个pr 更好了。

**Comment by xm-yu** [comment]
> 这个功能你可以根据组件的值自行实现的喔。或者能帮忙提个pr 更好了。

请问这个如何实现，有想过文档吗？我也遇到了这个问题

**Comment by xm-yu** [comment]
> 这个功能你可以根据组件的值自行实现的喔。或者能帮忙提个pr 更好了。

请问这个转换的规则是啥 没查到相关的转换规则

**Comment by wangzongming** [comment]
> 

这个我也不清楚
