### ISSUE TITLE
年选项的两个字段无法正确渲染

### ISSUE THREAD

**Issue by liwuxi** [wangzongming/qnn-react-cron#20]
### 问题描述
其他时间都可以正常渲染，其中年的「从xx年开始，每x年执行一次」和「指定」两项无法正确回显；

`radio` 无法正确选中，`input`、`checkbox` 不会正确清除；

### 最简代码

```typescript
const [value, setValue] = useState<string>();

const onOk = (value: string) => {
    setValue(value);
}

<CronOrigin value={value} onOk={onOk} />;
```

**Comment by liwuxi** [comment]
还有在 Typescript 项目中会报

```
JSX element type 'CronOrigin' does not have any construct or call signatures.
```

修改
```
// ts 中引用的方式
import * as QnnCron form "qnn-react-cron"
```
无法解决该问题。

**Comment by wangzongming** [comment]
> 还有在 Typescript 项目中会报
> 
> ```
> JSX element type 'CronOrigin' does not have any construct or call signatures.
> ```
> 
> 修改
> 
> ```
> // ts 中引用的方式
> import * as QnnCron form "qnn-react-cron"
> ```
> 
> 无法解决该问题。

报错的意思可以理解为：CronOrigin 这个变量没有（因为你上面 as 的名字叫 QnnCron）

**Comment by liwuxi** [comment]
> > 还有在 Typescript 项目中会报
> > ```
> > JSX element type 'CronOrigin' does not have any construct or call signatures.
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > 修改
> > ```
> > // ts 中引用的方式
> > import * as QnnCron form "qnn-react-cron"
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > 无法解决该问题。
> 
> 报错的意思可以理解为：CronOrigin 这个变量没有（因为你上面 as 的名字叫 QnnCron）

Sorry，这个问题是我没描述清楚，实际上我的 import 名和使用名是一致的，但依旧会报这个错误。

以下是我的 tsconfig.json 配置

```json
{
  "compilerOptions": {
    "target": "ES2015",
    "module": "ES2015",
    "moduleResolution": "node",
    "importHelpers": true,
    "jsx": "react",
    "esModuleInterop": true,
    "sourceMap": true,
    "baseUrl": "./",
    "declaration": true,
    "declarationDir": "types",
    "outDir": "lib",
    "strict": true,
    "resolveJsonModule": true,
    "skipLibCheck": true,
    "allowSyntheticDefaultImports": true,
    "paths": {
      "@/*": ["src/*"],
      "@docs/*": ["docs/*"],
      "hdos-form-coms": ["src/index.tsx"]
    }
  },
  "include": ["src/**/*", "docs/**/*", "typings.d.ts", "src/.umi/base"],
  "exclude": ["node_modules", "cjs", "lib", "es", "dist", "typings", "**/__test__", "test", "tests"]
}
```

**Comment by wangzongming** [comment]
> > > 还有在 Typescript 项目中会报
> > > ```
> > > JSX element type 'CronOrigin' does not have any construct or call signatures.
> > > ```
> > > 
> > > 
> > >     
> > >       
> > >     
> > > 
> > >       
> > >     
> > > 
> > >     
> > >   
> > > 修改
> > > ```
> > > // ts 中引用的方式
> > > import * as QnnCron form "qnn-react-cron"
> > > ```
> > > 
> > > 
> > >     
> > >       
> > >     
> > > 
> > >       
> > >     
> > > 
> > >     
> > >   
> > > 无法解决该问题。
> > 
> > 
> > 报错的意思可以理解为：CronOrigin 这个变量没有（因为你上面 as 的名字叫 QnnCron）
> 
> Sorry，这个问题是我没描述清楚，实际上我的 import 名和使用名是一致的，但依旧会报这个错误。
> 
> 以下是我的 tsconfig.json 配置
> 
> ```json
> {
>   "compilerOptions": {
>     "target": "ES2015",
>     "module": "ES2015",
>     "moduleResolution": "node",
>     "importHelpers": true,
>     "jsx": "react",
>     "esModuleInterop": true,
>     "sourceMap": true,
>     "baseUrl": "./",
>     "declaration": true,
>     "declarationDir": "types",
>     "outDir": "lib",
>     "strict": true,
>     "resolveJsonModule": true,
>     "skipLibCheck": true,
>     "allowSyntheticDefaultImports": true,
>     "paths": {
>       "@/*": ["src/*"],
>       "@docs/*": ["docs/*"],
>       "hdos-form-coms": ["src/index.tsx"]
>     }
>   },
>   "include": ["src/**/*", "docs/**/*", "typings.d.ts", "src/.umi/base"],
>   "exclude": ["node_modules", "cjs", "lib", "es", "dist", "typings", "**/__test__", "test", "tests"]
> }
> ```

我在 ts 项目里面是正常使用的，不会报错，你自行排查下吧。

**Comment by wangzongming** [comment]
> ### 问题描述
> 其他时间都可以正常渲染，其中年的「从xx年开始，每x年执行一次」和「指定」两项无法正确回显；
> 
> `radio` 无法正确选中，`input`、`checkbox` 不会正确清除；
> 
> ### 最简代码
> ```ts
> const [value, setValue] = useState<string>();
> 
> const onOk = (value: string) => {
>     setValue(value);
> }
> 
> <CronOrigin value={value} onOk={onOk} />;
> ```

已解决 安装  1.0.2 版本即可

**Comment by liwuxi** [comment]
无法正确渲染问题还是存在

**Comment by liwuxi** [comment]
> > 无法正确渲染问题还是存在
> 
> 我这里测试没问题才发布的，确认你安装的版本，重新卸载安装，或者提供最小可复现代码。

```typescript react

import { useState } from 'react';
import reactLogo from './assets/react.svg';
import './App.css';
// import * as QnnCron from 'qnn-react-cron';
import QnnCron from 'qnn-react-cron';

function App() {
  const [count, setCount] = useState('');

  return (
    <div className="App">
      <QnnCron value={count} onOk={setCount} />
    </div>
  );
}

export default App;
````

**Comment by liwuxi** [comment]
> > 无法正确渲染问题还是存在
> 
> 我这里测试没问题才发布的，确认你安装的版本，重新卸载安装，或者提供最小可复现代码。

「从xx年开始，每x年执行一次」这个问题好了，「指定」还是有问题，`onOk` 后 `Radio` 切换到每年

**Comment by wangzongming** [comment]
> > > 无法正确渲染问题还是存在
> > 
> > 
> > 我这里测试没问题才发布的，确认你安装的版本，重新卸载安装，或者提供最小可复现代码。
> 
> 「从xx年开始，每x年执行一次」这个问题好了，「指定」还是有问题，`onOk` 后 `Radio` 切换到每年

在选择超过两个后确认存在问题，最新版中已修复
