### ISSUE TITLE
Module "./qnn-react-cron" does not exist in container.

### ISSUE THREAD

**Issue by disguiseFish** [wangzongming/qnn-react-cron#23]
import QnnReactCron from "qnn-react-cron";    

  <QnnReactCron
        value={value}
        onOk={(value) => {
          console.log("cron:", value);
        }}
        getCronFns={(_cronFns) => {
          cronFns = _cronFns;
        }}
        footer={[
          <Button
            key="cencel"
            style={{ marginRight: 10 }}
            onClick={() => {
              setValue(null);
            }}
          >
            重置
          </Button>,
          <Button
            key="getValue"
            type="primary"
            onClick={() => {
              setValue(cronFns.getValue());
            }}
          >
            生成
          </Button>
        ]}
      />

qnn-react-cron@0.8.6  按照demo使用，报错Module "./qnn-react-cron" does not exist in container.

**Comment by wangzongming** [comment]
这个不是组件报的错误吧。你先排查下问题出在哪了

**Comment by wangzongming** [comment]
最新版是 1.x 升级到最新版吧，最新版和旧版是兼容的

**Comment by disguiseFish** [comment]
升级到1.x 还是不行欸   我照着https://codesandbox.io/s/qnn-react-cron-fxvbp?file=/src/App.js:358-1003 写的  也是用的里面的数据也不行

**Comment by disguiseFish** [comment]
解决了....mfsu的原因。。。
