### ISSUE TITLE
点击下拉框无法查看下拉信息

### ISSUE THREAD

**Issue by zaixia** [wangzongming/qnn-react-cron#3]
你好，我在使用此插件时，点击下拉框，下拉信息会快速展开并关闭，只有鼠标左键按住并移动到下拉列表才能查看内容。这种交互和antd不同，是否可以优化。

**Comment by wangzongming** [comment]
你好，本组件只提供一个面板功能，嵌入到 antd 下拉面板中需要配和 antd 下拉组件的 open 属性实现。
