### ISSUE TITLE
为什么每小时的表达式和每秒钟是一样的呢?

### ISSUE THREAD

**Issue by loveAndPeace11** [wangzongming/qnn-react-cron#34]

**Comment by wangzongming** [comment]
这个问题说出来你可能不太想接受，但不得不告诉你，
因为组件默认让每个面板都选择了每一（秒/分/时 ...）。
理论组件应该都将各个面板指向的默认选项都设置为 不指定 这个选项上。
但可能考虑到大部分情况下放到 每一X 这个选项上会更方便（我想应该是这么设计的）。
要解决你这问题可以直接把所有面板都指定到不指定，然后在年或者秒上面进行选择某个选项。
你也可以默认给组件一个 value 值，把所有面板都置为 不指定。
