### ISSUE TITLE
时分秒 设置为不指定后的cron语法错误

### ISSUE THREAD

**Issue by zx490336534** [wangzongming/qnn-react-cron#36]
时分秒 设置为不指定后的cron语法错误

**Comment by wangzongming** [comment]
根据你的描述，我将 value 设置为： ? ? ? * * ? *  但是并没有报错

**Comment by zx490336534** [comment]
![image](https://github.com/wangzongming/qnn-react-cron/assets/29444463/1c4390b9-dacf-4482-a0b4-5ace0d434aa2)
https://crontab.guru/#

> 根据你的描述，我将 value 设置为： ? ? ? * * ? * 但是并没有报错

**Comment by zx490336534** [comment]
我找了几个cron生成的网站前三个都不支持?
我这边的后端cron校验也会报错

**Comment by wangzongming** [comment]
我这边用的 xxjob 解析的。

**Comment by wangzongming** [comment]
或者前端直接隐藏这三个面板下的 不指定，参考：https://github.com/wangzongming/qnn-react-cron/issues/30
