### ISSUE TITLE
周选择指定星期几样式有误

### ISSUE THREAD

**Issue by lius14** [wangzongming/qnn-react-cron#37]
指定“星期一、、星期二、...、星期六”样式挤在一起

**Comment by wangzongming** [comment]
提供复现代码和截图。我本地没有问题，你那也许是应该是 antd 样式或者项目中写的别的样式导致的。
![image](https://github.com/wangzongming/qnn-react-cron/assets/27466569/0c9ffc2b-0894-4988-ac7c-7626bd1ada04)
