### ISSUE TITLE
样式覆盖了antd自定义的主题色

### ISSUE THREAD

**Issue by xuan085** [wangzongming/qnn-react-cron#4]
你好，我这边是自定义antd的主题色，但引入该插件后覆盖了我自定义antd主题色，请问如何解决

**Comment by umimori13** [comment]
的确，引入本库的发布版本，然后里面会导入的有antd的.css文件，会覆盖所有对应自定义的东西（包括body等），即便一开始就没有导入antd的css/less。

**Comment by wangzongming** [comment]
> 的确，引入本库的发布版本，然后里面会导入的有antd的.css文件，会覆盖所有对应自定义的东西（包括body等），即便一开始就没有导入antd的css/less。

我刚才发布了一版@0.4.3，使用 antd 的 less 打包。可以尝试下是否还存在全局样式被覆盖的问题，如果没问题我就关闭这个问题了。

**Comment by xuan085** [comment]
更新了版本0.4.3，没问题了，感谢
