### ISSUE TITLE
组件底层是否可以支持下依赖 value 默认选中激活的 Tab

### ISSUE THREAD

**Issue by louhaojie99** [wangzongming/qnn-react-cron#40]
看了下组件实现，回显组件没有处理依赖 value 值默认选中对应的 Tab

作者是否可以支持下

![image](https://github.com/wangzongming/qnn-react-cron/assets/61346611/0ab18560-e1ff-409a-826a-61ad57b2083a)

**Comment by louhaojie99** [comment]
看起来作者不太有时间，基于这个开源库做了重构版（进行中~）：

https://github.com/louhaojie99/react-cron-select

**Comment by wangzongming** [comment]
很抱歉，为了保证组件的稳定性，需求类的问题并不会随时更新。如果着急克隆一个仓库是一个明智的决定。 在本组件的最新版已经支持了你说的这个需求。
