### ISSUE TITLE
在Form表单中使用disabled属性

### ISSUE THREAD

**Issue by Loveapleace** [wangzongming/qnn-react-cron#41]
我有什么办法可以在添加不可编辑属性，让我的表达式组件无法修改值吗

**Comment by wangzongming** [comment]
有的，手动更改 css 样式为灰色，然后监听 onChange 事件，在事件中只设置固定值就行。

**Comment by Loveapleace** [comment]
可以，这也太骚了

**Comment by wangzongming** [comment]
记得点 star 哦

**Comment by Loveapleace** [comment]
有一个tabs切换的问题，我无法知道tabs什么时候切换，导致了我没有一个新的时机去监听新面板的onChange事件
