### ISSUE TITLE
去除 周的本月的最后一个 星期 ？执行一次

### ISSUE THREAD

**Issue by MrLishizhen** [wangzongming/qnn-react-cron#45]
我想将这一项去除应该怎么做

![image](https://github.com/wangzongming/qnn-react-cron/assets/49965948/4d726a3d-c77a-4a1b-b82e-8a48a3ff3f32)

**Comment by wangzongming** [comment]
看文档里面本地化配置 aStartTob.week2 返回空</>。或者直接用css
