### ISSUE TITLE
依赖报错

### ISSUE THREAD

**Issue by mayongkang1** [wangzongming/qnn-react-cron#46]
项目使用antd@5.13.2
引入qnn-react-cron后依赖冲突，想问一下老师怎么解决

**Comment by wangzongming** [comment]
很抱歉，这个问题老师暂时也没有去解决，目前仅支持 antd4,  v5版本在最近升

**Comment by mayongkang1** [comment]
> 很抱歉，这个问题老师暂时也没有去解决，目前仅支持 antd4, v5版本在最近升

好的感谢老师解答

**Comment by wangzongming** [comment]
2.x 版本已支持
