### ISSUE TITLE
升级成了2.0.0，在项目中使用报错，错误信息如下图，而且好像这个生成的cron表达式只能在后端的quartz框架中使用，如果在前端node-schedule框架中使用表达式则不生效

### ISSUE THREAD

**Issue by yecongling** [wangzongming/qnn-react-cron#47]
![image](https://github.com/wangzongming/qnn-react-cron/assets/31658223/d811d9f2-5dbd-4c89-9e46-870b9c640768)

**Comment by wangzongming** [comment]
对于报错问题提供一个复现案例我这边测试下，关于表达式值的格式如果不兼容其他框架自行转一下就行。

**Comment by yecongling** [comment]
https://github.com/yecongling/log-clean-react.git  这是我的项目地址，里面还是用的低版本的，升级2.0.0，启动就会出现问题
