### ISSUE TITLE
这里的星期支持配置成数字吗，1-7

### ISSUE THREAD

**Issue by jack-YangYang** [wangzongming/qnn-react-cron#49]
![E93FEC40-3EE8-40ae-AA29-84FD6D41AFBA](https://github.com/wangzongming/qnn-react-cron/assets/50625528/8ba05965-5d6c-4ad5-9015-a56ff518ad2d)

**Comment by wangzongming** [comment]
对于值的格式，插件仅提供内置的格式。不支持的自定义，需要自己转的。
