### ISSUE TITLE
【feat】能支持生成spring java cron吗？

### ISSUE THREAD

**Issue by zyclove** [wangzongming/qnn-react-cron#53]
希望界面配置后，能用spring cron执行。
https://tool.lu/crontab/

![image](https://github.com/user-attachments/assets/ed9ead5c-565a-4ef3-a1c2-489efb705f55)

**Comment by wangzongming** [comment]
默认生成出来的是 Java(Quartz) 的，后台自己网上复制一个方法转一下就行。
