### ISSUE TITLE
样式丢失

### ISSUE THREAD

**Issue by zhangyiqiu** [wangzongming/qnn-react-cron#6]
以readme中codesandbox的代码为模版，升级qnn-react-cron到0.5.3之后样式丢失

**Comment by wangzongming** [comment]
0.5.3 版本后的组件采用antd的按需加载，不在打包 antd 的样式。需要在 babel 插件中加入以下代码：
```
{
 // ...
plugins:[
  [
		"import",
		{
			libraryName: "antd",
			libraryDirectory: "es",
			style: "css",
		},
		"ant",
	]
]
}
      
```

或者在项目中引入 antd 样式，如下

`import "antd/dist/antd.min.css"`


你那边用我上述方式试一下，没问题我就关闭这个 iss 了

**Comment by zhangyiqiu** [comment]
我试试看

**Comment by zhangyiqiu** [comment]
感谢🙏，已解决
